runtime: nodejs22

instance_class: F2

env_variables:
  NODE_ENV: "production"
  DATABASE_URL: "file:./prisma/dev.db"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
